name: petbuddy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  material_design_icons_flutter: ^7.0.7296
  confetti: ^0.7.0
  flutter_svg: ^2.1.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/illustrations/undraw_dog_jfxm.svg
    - assets/illustrations/undraw_dog-walking_w27q (1).svg
    - assets/illustrations/undraw_dog-walking_w27q.svg
    - assets/illustrations/undraw_good-doggy_4ast.svg
    - assets/illustrations/undraw_playing-fetch_x508.svg
    - assets/illustrations/undraw_relaxing-walk_hvua.svg
  # fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-Bold.ttf
    #     # Optionally add more weights for Poppins
    #     - asset: assets/fonts/Poppins-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Poppins-Medium.ttf
    #       weight: 500